CREATE TABLE consumidor (
	cod INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
	cpf VARCHAR(30) NOT NULL,
	id VARCHAR(30) NOT NULL,
	ender VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	estado VARCHAR(30) NOT NULL,
	datanasc TIMESTAMP,
	prof VARCHAR(30) NOT NULL
)